#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo "Testing 🧪 and building 🏗 your project before pushing..."

echo ""
echo "Building 🏗🧱 your project 👷🏼‍🏡"

npm run build ||
{
  echo "❌ Build failed. Aborting push."
  false;
}

echo "✅  Build passed."

echo ""
echo "Everything is fire 🔥🔥🔥"
echo "Pushing to the moon 🚀🚀🚀"
echo ""
