#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo "Styling ✏️ and checking ✅  code 🖥 format 📝 in your project before committing..."

# Check tsconfig standards
npm run check-types ||
{
  echo "❌ TypeScript check failed. Aborting commit."
  false;
}

echo "✅  TypeScript check passed."

# Check Prettier standards
npm run check-format ||
{
  echo "❌ Prettier check failed. Aborting commit."
  false;
}

echo "✅  Prettier check passed."

# Check ESLint standards
npm run check-lint ||
{
  echo "❌ ESLint check failed. Aborting commit."
  false;
}

echo "✅  ESLint check passed."

echo ""
echo "Everything is fire 🔥🔥🔥"
echo "Committing to the moon 🚀🚀🚀"
echo ""
